version: '3.1'
services:
  db:
    image: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  web:
    build: .
    command: python manage.py runserver
    # environment:
    #   - ENV: "docker"